from collections.abc import Callable
from dataclasses import dataclass
from datetime import date, datetime
from typing import Protocol, Self

from appachas.contexts.groups.shared.domain.models import Group, Member, Movement


@dataclass(frozen=True)
class Access:
    token_hash: str
    session_hash: str | None = None


@dataclass(frozen=True)
class Actor:
    member_id: str
    is_creator: bool


class Clock(Protocol):
    def now(self) -> datetime: ...
    def today(self, timezone: str) -> date: ...


class Tokens(Protocol):
    def generate(self) -> tuple[str, str]: ...
    def identifier(self) -> str: ...


class Repository(Protocol):
    def get(self, token_hash: str, *, lock: bool) -> tuple[Group, bool] | None: ...
    def create(self, group: Group, creator_hash: str, member_hash: str) -> None: ...
    def save_group(self, group: Group) -> None: ...
    def save_member(self, group_id: str, member: Member) -> None: ...
    def delete_member(self, member_id: str) -> None: ...
    def save_movement(self, group_id: str, movement: Movement) -> None: ...
    def delete_movement(self, movement_id: str) -> None: ...
    def delete_group(self, group_id: str) -> None: ...
    def expiry_candidates(self) -> list[Group]: ...


class UnitOfWork(Protocol):
    @property
    def repository(self) -> Repository: ...

    def __enter__(self) -> Self: ...
    def __exit__(self, exc_type, exc_value, traceback) -> bool | None: ...


UnitOfWorkFactory = Callable[[], UnitOfWork]
